### PR TITLE
[Bug] Posts body render their HTML name or codes instead of displaying symbols 

### LINKED ISSUE #108: FE - Posts body render their HTML name or codes instead of displaying symbols (React Markdown)
Example:
Image

- Symbols like &, \, ", ', etc. are rendering as shown.
- React-Markdown and Remark-GFM have already been added to the client side
- Use this to enhance the Body of the posts.
- Ensure that tags still work properly.
- Ensure truncating still works

### PR DESCRIPTION
**Pull request by Priyadharshini0101**
Resolves #108 
- Added  HTML entity package to o decode special characters in post body
- Implemented React Markdown to render posts body
- Tags are now accurately detected and extracted after formatting is fixed

### CODE REVIEW

File: client/src/assets/components/posts/PostBody.jsx [hunk 1]
```diff
@@ -1,26 +1,34 @@
...
+    //                     className="text-primary hover:underline"
+    //                 >
+    //                     {word + ' '}
+    //                 </Link>
+    //             );
+    //         }
+    //         return <span key={i}>{word + ' '}</span>;
+    //     });
+    // };
+
```
Comment (alvarotorrestx) [inline client/src/assets/components/posts/PostBody.jsx]: Since it seems to be functional, let's go ahead and remove this and carry on with your updates. 😄

File: client/src/assets/components/posts/PostBody.jsx [hunk 2]
```diff
@@ -1,26 +1,34 @@
...
-                    >
-                        {word + ' '}
-                    </Link>
-                );
-            }
-            return <span key={i}>{word + ' '}</span>;
-        });
+      return text.replace(/(^|\s)(#\w+)/g, (_, space, tag) => {
+        const tagText = tag.replace(/[^\w#]/g, '').slice(1).toLowerCase();
+        return `${space}[${tag}](/tags/${tagText})`;
```
Comment (alvarotorrestx) [inline client/src/assets/components/posts/PostBody.jsx]: Can you comment this out for future use and create one with just a link with "#" so it doesn't forward to a page yet? We haven't implemented that feature just yet.

**Review by alvarotorrestx — CHANGES_REQUESTED** [review]
This looks fantastic! You've done a great job. Just some small changes since we're still early in production and it should be good to merge! 😄

**Comment by alvarotorrestx** [comment]
Thanks so much for this! This is looking great! And you helped out a lot with the video on testing and helped see where there might be an overflow in the future.

Just left a small update for changing but should be ready for implementing after.

If you'd like to continue... we could use further implementations on this like creating the list such as 
- This

or code blocks 
```
like this
```

But I'll await and see what you're interested in. Thanks again @Priyadharshini0101 😄

**Comment by Priyadharshini0101** [comment]
Thanks for reviewing my changes. I’ve updated the requested changes. Yes, I’m definitely interested! and I’m happy to help with the next part!

**Comment by alvarotorrestx** [comment]
Fantastic work, thank you so much for your contribution! 😀 

I'm so glad you want to continue! Go ahead and continue your work and I'll rename the issue and keep you assigned to it and PR with your updates 😄  @Priyadharshini0101
